### PR TITLE
Use expressive helpers

### PR DESCRIPTION
**Pull request by geerteltink**
- [x] Use expressive helpers in stead of injecting the router.
- [x] Add new url helper to generate absolute url for given route.
- [x] Add new absolute_url helper to generate absolute url for given path.
- [x] Add documentation.
- [x] Update/fix tests.

Optionally: Remove TwigExtension from TwigRenderFactory into its own factory and make it optional via the twig extension config.

### CODE REVIEW

**Comment by geerteltink** [comment]
I've updated the tests but there is a skipped test in TwigRendererFactoryTest, the last one.

> ....................S
> OK, but incomplete, skipped, or risky tests!
> Tests: 54, Assertions: 182, Skipped: 1.

I can't figure out why.

/cc @weierophinney @samsonasik

**Comment by geerteltink** [comment]
Also there is still the question if its useful to remove TwigExtension from TwigRenderFactory into its own factory and make it optional via the twig extension config.

**Comment by weierophinney** [comment]
> I've updated the tests but there is a skipped test in TwigRendererFactoryTest

I've isolated it: the test `testRaisesExceptionForInvalidConfigService()` was defining a `@depends` annotation, when it really needed a `@dataProvider` annotation. Interestingly, when I make that change, those tests all fail. I'm going to work on those in a separate PR.

**Comment by weierophinney** [comment]
@xtreamwayz #9 resolves the skipped tests.

**Comment by weierophinney** [comment]
> Also there is still the question if its useful to remove TwigExtension from TwigRenderFactory into its own factory and make it optional via the twig extension config.

I'd argue we should have it enabled by default; users can create their own `TwigRendererFactory` if they do not want to use it (or override the new `TwigExtensionFactory` to override the extension(s)).

**Comment by weierophinney** [comment]
@xtreamwayz Rebase to pick up the fix for the skipped tests. :smile:

**Comment by geerteltink** [comment]
Rebased.

Just in case... don't make a release yet. I've got a second feature coming very soon.

**Comment by weierophinney** [comment]
Merged to develop for release with 1.1.0.

**Pull request closed without merging**
